package com.archhub.hubcreatepolicy

import com.arch.fpl.hub.model.QuoteRequest;
import com.arch.fpl.hub.model.common.Policy;

rule "Row 1 UpdatePolicyCoverageDirectMappingDIROFF"
	agenda-group "Update-Policy"
	salience 8
	dialect "mvel"
	when
		$quoteRequest: QuoteRequest(policyProtection.diroff_2004 == true);
		$policy: Policy();
	then
		$policy.getPolicyCoverage().get(0).setLimit1Amt($quoteRequest.getPolicyDirectorsAndOfficers().getDirOffLmtAmt_9002().toString());
		$policy.getPolicyCoverage().get(0).setDeductible2Amt($quoteRequest.getPolicyDirectorsAndOfficers().getDirOffRetAmt_9011().toString());		
		$policy.getPolicyCoverage().get(0).setLitigationDate1($quoteRequest.getPolicyInsuranceHistory().getDirOffPrPendLitDt_8014());
end

rule "Row 2 UpdatePolicyCoverageDirectMappingEPL"
	agenda-group "Update-Policy"
	salience 8
	dialect "mvel"
	when
		$quoteRequest: QuoteRequest(policyProtection.epl_2005 == true);
		$policy: Policy();
	then
	    $policy.getPolicyCoverage().get(1).setLitigationDate1($quoteRequest.getPolicyInsuranceHistory().getEplPrPendLitDt_8020());
	    $policy.getPolicyCoverage().get(10).setLitigationDate1($quoteRequest.getPolicyInsuranceHistory().getEplPrPendLitDt_8020());
end

rule "Row 3 UpdatePolicyCoverageDirectMappingFID"
	agenda-group "Update-Policy"
	salience 8
	dialect "mvel"
	when
		$quoteRequest: QuoteRequest(policyProtection.fiduciary_2006 == true);
		$policy: Policy();
	then
		$policy.getPolicyCoverage().get(2).setLitigationDate1($quoteRequest.getPolicyInsuranceHistory().getFidPrPendLitDt_8026());
end

