package com.archhub.hubcreatepolicy;

import com.arch.fpl.hub.model.QuoteRequest;
import com.arch.fpl.hub.model.clearance.response.SubmissionClearanceResponseData;
import com.arch.fpl.hub.model.common.QuoteProcessRequestor;
import com.arch.fpl.hub.model.common.Policy;
import com.arch.fpl.hub.model.common.PolicyCoverage;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Predicate;
import java.math.BigDecimal;
import java.math.RoundingMode;


function Predicate<PolicyCoverage> covCodeUpdate(String covIndicator) {
 //Coverage Indicator 
		        Predicate<PolicyCoverage> condition = sc -> sc.getCoverageCd().equalsIgnoreCase(covIndicator);
		        
     return condition ;
 }
 
 function String covDecimalToStringRounded(String inputString) {
 
        String outPutString = new BigDecimal(inputString).setScale(2, RoundingMode.HALF_UP).toString();
		        
     return outPutString ;
 }
 
 
rule "Update Policy Derived Value DIROFF"
	agenda-group "Update-Policy"
	salience 7
	when
	$policy: Policy();
	$quoteRequest: QuoteRequest(getPolicyProtection().getDiroff_2004() == true)
	$quoteRequestor: QuoteProcessRequestor(getQuoteRequestorCode() == "HIP")
	then
		$policy.getPolicyCoverage().get(0).setCoverageCd("DIROFF");
		$policy.getPolicyCoverage().get(0).setExtAction("A");
		$policy.getPolicyCoverage().get(0).setID(null);
		$policy.getPolicyCoverage().get(0).setLitigationDate1Desc("ED");
		$policy.getPolicyCoverage().get(0).setPreverpPremOverrideInd("N");
		
end 

rule "Update Policy Derived Value EMPRLB"
	agenda-group "Update-Policy"
	salience 7
	when
	$policy: Policy();
	$quoteRequest: QuoteRequest(getPolicyProtection().getEpl_2005() == true)
	$quoteRequestor: QuoteProcessRequestor(getQuoteRequestorCode() == "HIP")
	then
		$policy.getPolicyCoverage().get(1).setCoverageCd("EMPRLB");
		$policy.getPolicyCoverage().get(1).setExtAction("A");
		$policy.getPolicyCoverage().get(1).setID(null);
		$policy.getPolicyCoverage().get(1).setPreverpPremOverrideInd("N");
		
end 

rule "Update Policy Derived Value FIDCRY"
	agenda-group "Update-Policy"
	salience 7
	when
	$policy: Policy();
	$quoteRequest: QuoteRequest(getPolicyProtection().getFiduciary_2006() == true)
	$quoteRequestor: QuoteProcessRequestor(getQuoteRequestorCode() == "HIP")
	then
		$policy.getPolicyCoverage().get(2).setCoverageCd("FIDCRY");
		$policy.getPolicyCoverage().get(2).setExtAction("A");
		$policy.getPolicyCoverage().get(2).setID(null);
		$policy.getPolicyCoverage().get(2).setPreverpPremOverrideInd("N");
		
		
end 

rule "Update Policy Derived Value CREMTA"
	agenda-group "Update-Policy"
	salience 7
	when
	$policy: Policy();
	$quoteRequest: QuoteRequest(getPolicyProtection().getCrime_2007() == true)
	$quoteRequestor: QuoteProcessRequestor(getQuoteRequestorCode() == "HIP")
	then
		$policy.getPolicyCoverage().get(3).setCoverageCd("CREMTA");
		$policy.getPolicyCoverage().get(3).setExtAction("A");
		$policy.getPolicyCoverage().get(3).setID(null);
		$policy.getPolicyCoverage().get(3).setPreverpPremOverrideInd("N");
		
		$policy.getPolicyCoverage().get(4).setCoverageCd("CRCFRF");
		$policy.getPolicyCoverage().get(5).setCoverageCd("CRCPRB");
		$policy.getPolicyCoverage().get(6).setCoverageCd("CRCURG");
		$policy.getPolicyCoverage().get(7).setCoverageCd("CRFRGE");
		$policy.getPolicyCoverage().get(8).setCoverageCd("CRINPC");
		$policy.getPolicyCoverage().get(9).setCoverageCd("CROTPD");
		
end 
 
rule "Update Policy Remove empty policy coverage nodes"
	agenda-group "Update-Policy"
	salience 7
	when
	$policy: Policy();
	$quoteRequestor: QuoteProcessRequestor(getQuoteRequestorCode() == "HIP")
	then
		$policy.getPolicyCoverage().removeIf(covCodeUpdate("N"));
		
end

rule "Update Policy Derived Value SubmissionStatus"
	agenda-group "Update-Policy"
	salience 7
	when
			$policy: Policy();
			$quoteRequestor: QuoteProcessRequestor(getQuoteRequestorCode() == "HIP")
			$subClrResponse: SubmissionClearanceResponseData(getCleared() == "Y")
	then
			$policy.setSubmissionStatus("WORKING");
			
end

rule "Update Policy Derived Value Rounding decimals and PW dependent Fields"
	agenda-group "Update-Policy"
	salience 7
	when
			$policy: Policy();
			$quoteRequestor: QuoteProcessRequestor(getQuoteRequestorCode() == "HIP")
	then
			$policy.setTotalRevenue(covDecimalToStringRounded($policy.getTotalRevenue()));
			$policy.setRatableAssets(covDecimalToStringRounded($policy.getRatableAssets()));
			$policy.setTotalAssets(covDecimalToStringRounded($policy.getTotalAssets()));
			
			//default values added based on sample policy# PCD100150100
			$policy.setSICCode("5045");
			$policy.setNAICSCd("425110");
			$policy.setDOPMinFactor("0.90");
			$policy.setDOPMaxFactor("1.30");
			
	end





