//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.07 at 04:49:57 PM EDT 
//


package com.arch.fpl.hub.model.clearance.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AccountNumber" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="Cleared" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MCID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Messages">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Message" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RefId" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="SubmissionNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accountNumber",
    "cleared",
    "mcid",
    "messages",
    "refId",
    "submissionNumber"
})
@XmlRootElement(name = "SubmissionClearanceRequestData")
public class SubmissionClearanceResponseData {

    @XmlElement(name = "AccountNumber", required = true)
    protected Object accountNumber;
    @XmlElement(name = "Cleared", required = true)
    protected String cleared;
    @XmlElement(name = "MCID", required = true)
    protected String mcid;
    @XmlElement(name = "Messages", required = true)
    protected Messages messages;
    @XmlElement(name = "RefId")
    @XmlSchemaType(name = "unsignedShort")
    protected int refId;
    @XmlElement(name = "SubmissionNumber")
    @XmlSchemaType(name = "unsignedInt")
    protected String submissionNumber;

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAccountNumber(Object value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the cleared property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCleared() {
        return cleared;
    }

    /**
     * Sets the value of the cleared property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCleared(String value) {
        this.cleared = value;
    }

    /**
     * Gets the value of the mcid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMCID() {
        return mcid;
    }

    /**
     * Sets the value of the mcid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMCID(String value) {
        this.mcid = value;
    }

    /**
     * Gets the value of the messages property.
     * 
     * @return
     *     possible object is
     *     {@link SubmissionClearanceResponseData.Messages }
     *     
     */
    public Messages getMessages() {
        return messages;
    }

    /**
     * Sets the value of the messages property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmissionClearanceResponseData.Messages }
     *     
     */
    public void setMessages(Messages value) {
        this.messages = value;
    }

    /**
     * Gets the value of the refId property.
     * 
     */
    public int getRefId() {
        return refId;
    }

    /**
     * Sets the value of the refId property.
     * 
     */
    public void setRefId(int value) {
        this.refId = value;
    }

    /**
     * Gets the value of the submissionNumber property.
     * 
     */
    public String getSubmissionNumber() {
        return submissionNumber;
    }

    /**
     * Sets the value of the submissionNumber property.
     * 
     */
    public void setSubmissionNumber(String value) {
        this.submissionNumber = value;
    }


    

}
