package com.archhub.hubcreatepolicy;

import com.arch.fpl.hub.model.common.QuoteProcessRequestor;
import com.arch.fpl.hub.model.common.Policy;
import com.arch.fpl.hub.model.quote.response.QuoteStatus;
import com.arch.fpl.hub.model.common.AdhocQuoteDetails;


rule "Decline Policy Derived Value Rule -1"
	agenda-group "Decline-Policy"
	salience 7
	when
			$policy: Policy();
			$quoteRequestor: QuoteProcessRequestor(getQuoteRequestorCode() == "HIP")
			$quoteStatus: QuoteStatus(statusCode == "Decline")
			$adhocQuoteDetails: AdhocQuoteDetails()
	then
		    $policy.setExtAction("U");
		    $policy.setCTID("1");
		    $policy.setID("1");
		    $policy.setVERSIONNO("1");
			$policy.setStageReasonCd($adhocQuoteDetails.getDeclineReasonCd());
end





