package com.arch.fpl.hub.model.clearance.request;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DataObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public DataObject() {
	}

}